export const COMPANY_CONFIGS = {
  IS_AUTO_APPROVE_BOOKING_FLIGHT: 'IS_AUTO_APPROVE_BOOKING_FLIGHT',
  IS_AUTO_APPROVE_BOOKING_HOTEL: 'IS_AUTO_APPROVE_BOOKING_HOTEL',
  IS_AUTO_APPROVE_BOOKING_JOURNEY: 'IS_AUTO_APPROVE_BOOKING_JOURNEY',
};

export const COMPANY_CONFIGS_LABELS = {
  IS_AUTO_APPROVE_BOOKING_FLIGHT: 'Is Auto Approve Booking Flight',
  IS_AUTO_APPROVE_BOOKING_HOTEL: 'Is Auto Approve Booking Hotel',
  IS_AUTO_APPROVE_BOOKING_JOURNEY: 'Is Auto Approve Booking Journey',
};
