export const DEFAULT_ERROR_MESSAGE = 'Sorry, something went wrong.';

export const CLIENT_SOURCE = 'BIZTRIP';

export const DEFAULT_PAGE_SIZE = 10;

export const ROLE_COMPANY_ADMIN = 'COMPANY_ADMIN';
export const ROLE_USER = 'USER';
export const ROLE_APPROVER = 'APPROVER';

export const ADULT_AGE = 12;
export const CHILD_AGE = 2;
export const INFANT_AGE = 0;
export const ADULT_TYPE = 'ADULT';
export const CHILD_TYPE = 'CHILD';
export const INFANT_TYPE = 'INFANT';

export const FLIGHT_CLASS_FIRST_CLASS = 'FIRST_CLASS';
export const FLIGHT_CLASS_PREMIUM_ECONOMY = 'PREMIUM_ECONOMY';
export const FLIGHT_CLASS_ECONOMY = 'ECONOMY';
export const FLIGHT_CLASS_BUSINESS = 'BUSINESS';

export const FLIGHT_CLASS_LABELS: Record<string, string> = {
  [FLIGHT_CLASS_FIRST_CLASS]: 'First Class',
  [FLIGHT_CLASS_BUSINESS]: 'Business',
  [FLIGHT_CLASS_PREMIUM_ECONOMY]: 'Premium Economy',
  [FLIGHT_CLASS_ECONOMY]: 'Economy',
};

export const FLIGHT_CLASS_OPTIONS = [
  { label: FLIGHT_CLASS_LABELS[FLIGHT_CLASS_FIRST_CLASS], value: FLIGHT_CLASS_FIRST_CLASS },
  { label: FLIGHT_CLASS_LABELS[FLIGHT_CLASS_PREMIUM_ECONOMY], value: FLIGHT_CLASS_PREMIUM_ECONOMY },
  { label: FLIGHT_CLASS_LABELS[FLIGHT_CLASS_ECONOMY], value: FLIGHT_CLASS_ECONOMY },
  { label: FLIGHT_CLASS_LABELS[FLIGHT_CLASS_BUSINESS], value: FLIGHT_CLASS_BUSINESS },
];

export const FLIGHT_CLASS_RANK: Record<string, number> = {
  [FLIGHT_CLASS_ECONOMY]: 1,
  [FLIGHT_CLASS_PREMIUM_ECONOMY]: 2,
  [FLIGHT_CLASS_BUSINESS]: 3,
  [FLIGHT_CLASS_FIRST_CLASS]: 4,
};

export const AIRLINE_CODE_GARUDA = 'GA';

export const AIRLINE_CODES_WITH_POLICY_LIMITS = [AIRLINE_CODE_GARUDA];

export const BOOKING_STATUS_APPROVED = 'APPROVED';
export const BOOKING_STATUS_REJECTED = 'REJECTED';
export const BOOKING_STATUS_BOOKED = 'BOOKED';
export const BOOKING_STATUS_CANCELLED = 'CANCELLED';
export const BOOKING_STATUS_ISSUED = 'ISSUED';

export const DEPOSIT_CODE_FLIGHT = 'WALLET_FLIGHT';
export const DEPOSIT_CODE_HOTEL = 'WALLET_HOTEL';
