import { ROLE_APPROVER, ROLE_COMPANY_ADMIN, ROLE_USER } from './common';

export const PERMISSIONS = {
  APPROVAL: 'approval',
  CONFIG_EMPLOYEE: 'config_employee',
  CONFIG_TRAVEL_POLICY: 'config_travel_policy',
  CONFIG_COMPANY: 'config_company',
  MONITORING_DEPOSIT: 'monitoring_deposit',
  MONITORING_CREDIT: 'monitoring_credit',
};

export const PERMISSIONS_BY_ROLE: Record<string, string[]> = {
  [ROLE_COMPANY_ADMIN]: [
    PERMISSIONS.CONFIG_EMPLOYEE,
    PERMISSIONS.CONFIG_TRAVEL_POLICY,
    PERMISSIONS.CONFIG_COMPANY,
    PERMISSIONS.MONITORING_DEPOSIT,
    PERMISSIONS.MONITORING_CREDIT,
  ],
  [ROLE_USER]: [],
  [ROLE_APPROVER]: [PERMISSIONS.APPROVAL],
};
